### ISSUE TITLE
The pre-trained model for DGT-ST's stage-1

### ISSUE THREAD

**Issue by jj-ccc** [yuan-zm/DGT-ST#2]
You have done some very interesting and impressive work. I would like to reproduce your results, but since GAN training is unstable, I would like to download your stage-1 pre-trained code. However, I have downloaded the model you provided, but I encountered an extraction error and cannot use the tar command to extract the tar file. I can only use unzip, but the extraction is incorrect. Could you please check this for me?

**Comment by yuan-zm** [comment]
Hi @jj-ccc,

You can directly load the upload checkpoints. The examples are given here.

1. https://github.com/yuan-zm/DGT-ST/blob/83195256f545e49a8b70de48ffded89793b5517b/README.md?plain=1#L102 
2. https://github.com/yuan-zm/DGT-ST/blob/83195256f545e49a8b70de48ffded89793b5517b/infer.py#L105).

Feel free to let me know if the above resolves your question.

**Comment by jj-ccc** [comment]
Hi，yuan-zm！
Wow, I mistakenly thought it was a compressed package! Thank you very much for your patient explanation!
